# You are given two strings s and t. 
# 
#  String t is generated by random shuffling string s and then add one more lett
# er at a random position. 
# 
#  Return the letter that was added to t. 
# 
#  
#  Example 1: 
# 
#  
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#  
# 
#  Example 2: 
# 
#  
# Input: s = "", t = "y"
# Output: "y"
#  
# 
#  
#  Constraints: 
# 
#  
#  0 <= s.length <= 1000 
#  t.length == s.length + 1 
#  s and t consist of lowercase English letters. 
#  
#  Related Topics Hash Table String Bit Manipulation Sorting 
#  👍 1752 👎 342


# leetcode submit region begin(Prohibit modification and deletion)
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        '''
        用加減法找出該字母
        '''
        res = ord(t[-1])    # 先轉換為數字
        for i in range(len(s)):
            res = res + ord(t[i]) - ord(s[i])  # +t-s
        return chr(res)  # 剩下的轉回字母
# leetcode submit region end(Prohibit modification and deletion)
